export type Honesty = "LIVE" | "ADVISORY" | "RESEARCH" | "ROADMAP" | "UNAVAILABLE";

export type AtlasRow = {
  id: string;
  n: number;
  szl: string;
  repo: string;
  leader: string;
  paper: string;
  paperUrl: string;
  repoUrl: string;
  leaderSummary: [string, string, string];
  delta: string;
  frontier: string;
  frontierId: string;
  live: boolean;
  honesty: Honesty;
  silhouette: string;
};

export const ATLAS: AtlasRow[] = [
  {
    id: "receipt-attn",
    n: 1,
    szl: "szl-receipt-attn",
    repo: "szl-holdings/szl-receipt-attn",
    leader: "FlashAttention (Tri Dao)",
    paper: "FlashAttention, NeurIPS 2022 · arXiv:2205.14135",
    paperUrl: "https://arxiv.org/abs/2205.14135",
    repoUrl: "https://github.com/Dao-AILab/flash-attention",
    leaderSummary: [
      "Dao, Fu, Ermon, Rudra, and Ré fused the softmax–matmul path into SRAM tiles so exact attention never materializes the N×N score matrix.",
      "FlashAttention-2 (2023) rebalanced work across warps; FlashAttention-3 (2024) targets Hopper async copy and FP8.",
      "The Dao-AILab CUDA/CuTe kernels are the field standard for exact attention throughput, not a governance artifact.",
    ],
    delta:
      "SZL silhouettes tiled fused attention in original Triton (head dim ≤ 32) and emits a SHA3-256 receipt onto UnifiedReceiptChain. CPU torch_reference is the honest fallback. No speedup claim. Not a rehost of Dao .cu, hopper/, or cute/.",
    frontier: "TileReceipt",
    frontierId: "tilereceipt",
    live: true,
    honesty: "LIVE",
    silhouette: "tiled fused attention",
  },
  {
    id: "block-kv",
    n: 2,
    szl: "szl-block-kv",
    repo: "szl-holdings/szl-block-kv",
    leader: "PagedAttention / vLLM",
    paper: "PagedAttention, SOSP 2023 · arXiv:2309.06180",
    paperUrl: "https://arxiv.org/abs/2309.06180",
    repoUrl: "https://github.com/vllm-project/vllm",
    leaderSummary: [
      "Kwon et al. virtualize the KV cache into non-contiguous blocks, the OS-paging trick that unlocked continuous batching.",
      "vLLM made that block table the serving primitive: prefix sharing, preemption, and high GPU occupancy follow from it.",
      "The category is memory management for throughput, not a witness over the table itself.",
    ],
    delta:
      "SZL ships an original paged-KV gather with a SHA3 digest of the block table. v0 is a labeled torch gather; the Triton page kernel is ROADMAP. Distinct from a11oy H2O eviction. No tokens/s claim. Not a vLLM rehost.",
    frontier: "BlockWitness",
    frontierId: "blockwitness",
    live: true,
    honesty: "LIVE",
    silhouette: "paged KV cache",
  },
  {
    id: "maskmod",
    n: 3,
    szl: "szl-maskmod",
    repo: "szl-holdings/szl-maskmod",
    leader: "FlexAttention (PyTorch)",
    paper: "FlexAttention · arXiv:2412.05496",
    paperUrl: "https://arxiv.org/abs/2412.05496",
    repoUrl: "https://pytorch.org/blog/flexattention/",
    leaderSummary: [
      "PyTorch FlexAttention lets you write score_mod(score, b, h, q_idx, kv_idx) and mask_mod, then compiles them to Flash-class kernels.",
      "BlockMask records block-level sparsity so fully masked tiles are skipped instead of just zeroed.",
      "The win is programmable attention at fused speed — still unsigned, still without a receipt of which mask ran.",
    ],
    delta:
      "szl-maskmod is an original score_mod + block-sparse mask path that receipts the mask digest. Not a rehost of flex_attention.py. No CUDA benches. A swapped mask cannot stay silent.",
    frontier: "ScoreMod Fiber",
    frontierId: "scoremod",
    live: true,
    honesty: "LIVE",
    silhouette: "score_mod + block mask",
  },
  {
    id: "yarqa-attn",
    n: 4,
    szl: "YARQA-ATTN",
    repo: "szl-holdings/YARQA-ATTN",
    leader: "SageAttention (Zhang et al.)",
    paper: "SageAttention, ICLR 2025 · arXiv:2410.02367",
    paperUrl: "https://arxiv.org/abs/2410.02367",
    repoUrl: "https://github.com/thu-ml/SageAttention",
    leaderSummary: [
      "Zhang, Wei, Huang, Zhang, Zhu, and Chen quantize QK to INT8 with smoothing so plug-and-play attention runs 2–5× over Flash without metric loss.",
      "SageAttention2/2++ push INT4 and Hopper; the category is quantized fused attention.",
      "It is a speed kernel. It does not partition sequences into independently receipted canals.",
    ],
    delta:
      "YARQA-ATTN is not quantized attention and not a fourth Flash/Flex/paged stack. Original cut: contiguous canals (Quechua yarqa = irrigation canal), attend only inside each compartment, receipt the partition. GPU cubins UNAVAILABLE this session. CPU torch_compartment is import-LIVE.",
    frontier: "Canal Compartment",
    frontierId: "canal",
    live: true,
    honesty: "LIVE",
    silhouette: "quantized / compartment attention",
  },
  {
    id: "governed-norm",
    n: 5,
    szl: "szl-governed-norm",
    repo: "szl-holdings/szl-governed-norm",
    leader: "RMSNorm / LayerNorm",
    paper: "RMSNorm · arXiv:1910.07467 · LayerNorm 2016",
    paperUrl: "https://arxiv.org/abs/1910.07467",
    repoUrl: "https://github.com/bzhangGo/rmsnorm",
    leaderSummary: [
      "Ba, Kiros, and Hinton’s LayerNorm (2016) re-centers and re-scales the last dim; it is still the transformer default in many stacks.",
      "Zhang and Sennrich’s RMSNorm (2019) drops the mean and scales by RMS — Llama, Qwen, and Gemma 2 all ship it.",
      "Every framework has a fused kernel. None of them emit an output digest you can re-walk.",
    ],
    delta:
      "Governed RMS/LayerNorm matches torch references and optionally chains a SHA3 of the rounded output. Standalone repo is DEPRECATED into szl-lambda-gate.governed_norm. No speedup. The digest is integrity, not authorship.",
    frontier: "NormFiber",
    frontierId: "normfiber",
    live: true,
    honesty: "ADVISORY",
    silhouette: "normalization",
  },
  {
    id: "lambda-gate",
    n: 6,
    szl: "szl-lambda-gate",
    repo: "szl-holdings/szl-lambda-gate",
    leader: "Geometric mean / Choquet / fuzzy aggregation",
    paper: "UN HDI 2010 · OECD composite indicators 2008",
    paperUrl: "https://hdr.undp.org/content/human-development-report-2010",
    repoUrl: "https://www.oecd.org/en/publications/handbook-on-constructing-composite-indicators-methodology-and-user-guide_9789264043466-en.html",
    leaderSummary: [
      "The weighted geometric mean is the less-compensatory aggregator behind the 2010 HDI switch and the OECD composite-indicator handbook.",
      "Choquet and Sugeno integrals add fuzzy measures so criteria can interact; ELECTRE’s veto lets one failing axis block a pass.",
      "These are established decision tools. None of them carry a machine-checked uniqueness conjecture that stays OPEN on purpose.",
    ],
    delta:
      "Λ is WGM over [0,1] axes, fail-closed to 0 on any zero or non-finite axis, with A1–A4 runtime checks. Uniqueness is Conjecture 1 — OPEN. The gate is advisory, never proven trust. yuyay_weights is SZL’s 13-axis form.",
    frontier: "Λ Zero-Veto",
    frontierId: "lambda",
    live: true,
    honesty: "ADVISORY",
    silhouette: "non-compensatory aggregation",
  },
  {
    id: "govsign",
    n: 7,
    szl: "govsign + provctl",
    repo: "szl-holdings/szl-govsign",
    leader: "in-toto / SLSA / Sigstore / DSSE",
    paper: "in-toto SEC 2019 · SLSA · Sigstore · DSSE",
    paperUrl: "https://in-toto.io/",
    repoUrl: "https://github.com/in-toto/in-toto",
    leaderSummary: [
      "in-toto attests each supply-chain step; SLSA grades that attestation from L1 (documented) to L3 (hardened builds).",
      "Sigstore adds keyless Fulcio identities and a Rekor transparency log; DSSE is the authenticated envelope (payloadType, payload, signatures).",
      "The stack signs artifacts and builds. It does not bind an advisory Λ verdict or an honest-null energy reading into the same envelope.",
    ],
    delta:
      "govsign attests a governance predicate (Λ, energy, decision) as DSSE/ECDSA-P256 with proven_trust locked false. provctl re-walks the receipt DAG and serializes in-toto v1 / SLSA v1 shapes. SLSA L1 honest, L2 roadmap. UNSIGNED is a first-class fallback, never a fake signature.",
    frontier: "GovEnvelope",
    frontierId: "govenvelope",
    live: true,
    honesty: "LIVE",
    silhouette: "supply-chain attestation",
  },
  {
    id: "khipu-1b",
    n: 8,
    szl: "SZL-Khipu-1.5B",
    repo: "szl-holdings/szl-forge",
    leader: "Llama 3.2 1B / Qwen2.5 1.5B / Gemma 2 2B",
    paper: "Llama 3.2 · Qwen2.5 · Gemma 2 model cards",
    paperUrl: "https://huggingface.co/meta-llama/Llama-3.2-1B",
    repoUrl: "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct",
    leaderSummary: [
      "Meta’s Llama 3.2 1B, Alibaba’s Qwen2.5 1.5B, and Google’s Gemma 2 2B are the small-instruct bases everyone fine-tunes.",
      "They are real pretrained weights with public evals and licenses that already cover the 1–2B edge slot.",
      "The field race is MMLU and tokens/s. Honest abstention is not a reported metric.",
    ],
    delta:
      "SZL-Khipu-1.5B is a QLoRA fine-tune, MEASURED_RESEARCH_ONLY, not a from-scratch pretrain. Held-out abstention is 2/6. Autonomous and high-stakes use is prohibited. Curriculum encodes MEASURED / REPORTED / UNKNOWN rather than a bigger base.",
    frontier: "AbstainGauge",
    frontierId: "abstain",
    live: false,
    honesty: "RESEARCH",
    silhouette: "small instruct LM",
  },
  {
    id: "szl-nemo",
    n: 9,
    szl: "szl-nemo",
    repo: "szl-holdings/szl-guardrail-receipt",
    leader: "NVIDIA NeMo Guardrails",
    paper: "NeMo Guardrails · NVIDIA 2023",
    paperUrl: "https://arxiv.org/abs/2310.10501",
    repoUrl: "https://github.com/NVIDIA-NeMo/Guardrails",
    leaderSummary: [
      "NeMo Guardrails (Colang) programs topical, jailbreak, and PII rails around an LLM runtime.",
      "Llama Guard and Guardrails AI occupy the same slot: a policy layer that allows or blocks generations.",
      "Decisions are logs. They are not a signed, hash-chained receipt that a third party can replay offline.",
    ],
    delta:
      "szl-nemo is a doctrine-wrapped Nemotron 3 Nano 4B Ollama recipe — a wrapper, not an SZL fine-tune. szl-guardrail-receipt wraps any guardrail callable and emits a DSSE decision receipt. UNSIGNED-honest if no key. Never fabricates a signature.",
    frontier: "ReceiptRail",
    frontierId: "receiptrail",
    live: false,
    honesty: "ADVISORY",
    silhouette: "LLM guardrails",
  },
  {
    id: "forge",
    n: 10,
    szl: "szl-forge",
    repo: "szl-holdings/szl-forge",
    leader: "Unsloth QLoRA",
    paper: "QLoRA, Dettmers et al. 2023 · Unsloth",
    paperUrl: "https://arxiv.org/abs/2305.14314",
    repoUrl: "https://github.com/unslothai/unsloth",
    leaderSummary: [
      "Dettmers et al. made 4-bit LoRA practical; Unsloth made it the default single-GPU fine-tune kit with fused kernels and lower VRAM.",
      "A recipe plus a merge does not by itself prove the published Hub bytes match the training run.",
      "The leader is speed-to-adapter. The missing piece is a fail-closed publication contract.",
    ],
    delta:
      "Forge sits on Unsloth and adds weight-hash bindings, signed training/eval receipts, and promotion state. A recipe is not a trained model. publication.json must match expected hashes or the gate stays NOT_READY. Not from-scratch pretraining.",
    frontier: "BindForge",
    frontierId: "bindforge",
    live: false,
    honesty: "LIVE",
    silhouette: "QLoRA fine-tune kit",
  },
  {
    id: "lutar-lean",
    n: 11,
    szl: "lutar-lean",
    repo: "szl-holdings/lutar-lean",
    leader: "Lean 4 / Mathlib",
    paper: "Lean 4 · mathlib4 · de Moura et al.",
    paperUrl: "https://lean-lang.org/",
    repoUrl: "https://github.com/leanprover-community/mathlib4",
    leaderSummary: [
      "Lean 4 plus mathlib4 is the production proof assistant for machine-checked mathematics.",
      "The community (and projects such as Xena / Terrence Tao’s formalizations) treat a sorry as a hole, not a theorem.",
      "The leader is general mathematics. It does not ship a governance aggregator whose uniqueness is locked OPEN.",
    ],
    delta:
      "lutar-lean formalizes the Λ aggregator: 749 declarations, 14 axioms, 163 tracked sorries, DOI 10.5281/zenodo.20434308. Uniqueness is Conjecture 1 — OPEN. A sorry cannot be painted green. Locked-proven formulas = exactly 8.",
    frontier: "SorryLedger",
    frontierId: "sorryledger",
    live: true,
    honesty: "ADVISORY",
    silhouette: "formal verification",
  },
  {
    id: "khipu-consensus",
    n: 12,
    szl: "khipu-consensus",
    repo: "szl-holdings/khipu-consensus",
    leader: "CRDT / BFT consensus",
    paper: "PBFT · HotStuff · Yjs / Automerge CRDTs",
    paperUrl: "https://pmg.csail.mit.edu/papers/osdi99.pdf",
    repoUrl: "https://github.com/yjs/yjs",
    leaderSummary: [
      "CRDTs (Shapiro; Yjs, Automerge) give AP collaboration without a leader. BFT (PBFT, HotStuff, Tendermint) gives agreement with n ≥ 3f+1.",
      "Both are general-purpose distributed systems. They do not bind an AI action hash to independent governance witnesses.",
      "A quorum of replicas is not a quorum of policy organs.",
    ],
    delta:
      "Khipu is 3-of-4 multi-party-witnessed AI: each witness DSSE-signs the same action hash with its own ECDSA P-256 key. One Byzantine or offline cord is tolerated. Safety is Conjecture 2, liveness Conjecture 3 — proof-deferred. Not a CRDT rehost.",
    frontier: "Khipu Quorum",
    frontierId: "khipu",
    live: true,
    honesty: "ADVISORY",
    silhouette: "BFT / CRDT agreement",
  },
  {
    id: "energy",
    n: 13,
    szl: "szl-energy-attest",
    repo: "szl-holdings/szl-energy-attest",
    leader: "CodeCarbon / Zeus",
    paper: "CodeCarbon · Zeus (ML.ENERGY)",
    paperUrl: "https://github.com/mlco2/codecarbon",
    repoUrl: "https://github.com/ml-energy/zeus",
    leaderSummary: [
      "CodeCarbon estimates kgCO2e from power models and a grid mix; Zeus measures and optimizes GPU joules for DNN training.",
      "Both are serious energy tools. When a meter is missing they often estimate rather than refuse.",
      "An estimate that looks like a measurement is the honesty failure SZL refuses.",
    ],
    delta:
      "Energy receipts are MEASURED-NVML joule deltas or honest UNAVAILABLE null. Never a fabricated joule. Grid carbon is REPORTED context, independent of joule status. Cheapest-watt placement is advisory.",
    frontier: "JouleNull",
    frontierId: "joulenull",
    live: false,
    honesty: "UNAVAILABLE",
    silhouette: "energy / carbon ML",
  },
  {
    id: "ouroboros",
    n: 14,
    szl: "szl-ouroboros",
    repo: "szl-holdings/szl-ouroboros",
    leader: "Ouroboros / bounded recursion / Bekenstein",
    paper: "Kiayias et al. Ouroboros · Bekenstein 1981",
    paperUrl: "https://arxiv.org/abs/1407.3833",
    repoUrl: "https://github.com/szl-holdings/ouroboros",
    leaderSummary: [
      "Cardano’s Ouroboros is a provably secure proof-of-stake protocol (Kiayias et al.), not an agent loop.",
      "The Bekenstein bound says a finite energy and radius imply a finite information capacity — a hard ceiling, not a metaphor.",
      "Bounded recursion in CS is the old idea that a loop needs a decreasing measure. Production agents often omit the measure.",
    ],
    delta:
      "szl-ouroboros is bounded loop-tax accounting: dual-witness emitters, a governance budget, MEASURED/DERIVED tax per hop. Not Cardano consensus and not a physics proof. The snake cannot eat past the bound; halt is fail-closed.",
    frontier: "Loop-Tax",
    frontierId: "looptax",
    live: true,
    honesty: "LIVE",
    silhouette: "bounded agent recursion",
  },
  {
    id: "anatomy",
    n: 15,
    szl: "szl-anatomy",
    repo: "szl-holdings/anatomy",
    leader: "digital twin / systems anatomy / observability mesh",
    paper: "Living Anatomy v5/v6 · SZL Holdings 2026",
    paperUrl: "https://github.com/szl-holdings/anatomy",
    repoUrl: "https://github.com/szl-holdings/anatomy",
    leaderSummary: [
      "Digital twins and observability meshes map a system as organs, buses, and sensors. They visualize health; they rarely fail-close a decision when one organ is down.",
      "The public SZL 3D atlas (Three.js, SLSA L1 static viz) is that map: HEART/YUYAY, YAWAR, YACHAY, OTel, Khipu skeleton, plus WILLAY conscience.",
      "A RUNNING Space is transport, not proof. Evidence Bay keeps transport, evidence, verification, and authority on separate rails.",
    ],
    delta:
      "szl-anatomy is the fail-closed integrity kernel of that body, not a Three.js rehost. HEART is advisory Λ, CIRCULATORY is the receipt chain, BRAIN is read-only YARQA, NERVOUS refuses fabricated joules, SKELETON is the locked-8 silhouette. Any DOWN organ or a WILLAY veto blocks the body. Λ stays Conjecture 1 OPEN. Energy UNAVAILABLE.",
    frontier: "Organ Integrity",
    frontierId: "organ",
    live: true,
    honesty: "LIVE",
    silhouette: "five-organ governed substrate",
  },
  {
    id: "chaski",
    n: 16,
    szl: "szl-chaski",
    repo: "szl-holdings/szl-khipu",
    leader: "Apache Kafka (Kreps, Narkhede, Rao)",
    paper: "Kafka: a Distributed Messaging System for Log Processing · NetDB 2011",
    paperUrl: "https://kafka.apache.org/documentation/#introduction",
    repoUrl: "https://github.com/apache/kafka",
    leaderSummary: [
      "Kafka is a durable, partitioned, replayable commit log. Producers append; consumers walk offsets. Order holds inside a partition.",
      "The category is throughput and retention for activity streams — LinkedIn’s original cut, now the default bus.",
      "A broker will retry a reorder. It will not hash-chain a runner FIFO and fail-close the drain.",
    ],
    delta:
      "Chaski is a fail-closed, hash-chained runner FIFO. drain(enqueueAll([], msgs)) = msgs is Lean F7. A swapped or dropped cord is BLOCKED, not retried. Not a Kafka rehost. No msgs/s claim.",
    frontier: "Chaski FIFO",
    frontierId: "chaski",
    live: true,
    honesty: "LIVE",
    silhouette: "ordered message log",
  },
  {
    id: "ayni",
    n: 17,
    szl: "szl-ayni",
    repo: "szl-holdings/szl-khipu",
    leader: "ResNet residual learning (He, Zhang, Ren, Sun)",
    paper: "Deep Residual Learning for Image Recognition · arXiv:1512.03385",
    paperUrl: "https://arxiv.org/abs/1512.03385",
    repoUrl: "https://github.com/KaimingHe/deep-residual-networks",
    leaderSummary: [
      "He et al. made identity skip connections the default residual bus: x_out = x_in + F(x_in), so a deep net can learn a perturbation of identity.",
      "Every modern backbone inherits that add. Conservation of the bus is not a reported metric.",
      "A silent skip leak still trains. It just stops being the map it claimed to be.",
    ],
    delta:
      "Ayni receipts Σ(out − in − F) = 0 on the residual bus. A scaled skip is a leak, and the bound fails closed. F11 locked. Not a ResNet rehost. No ImageNet claim.",
    frontier: "Ayni Reciprocity",
    frontierId: "ayni",
    live: true,
    honesty: "LIVE",
    silhouette: "residual skip connection",
  },
  {
    id: "shard",
    n: 18,
    szl: "szl-shard",
    repo: "szl-holdings/szl-khipu",
    leader: "Reed–Solomon / RAID-6 erasure coding",
    paper: "Polynomial Codes over Certain Finite Fields · SIAM 1960 · RFC 5510",
    paperUrl: "https://www.rfc-editor.org/rfc/rfc5510",
    repoUrl: "https://github.com/klauspost/reedsolomon",
    leaderSummary: [
      "Reed and Solomon (1960) evaluate a degree < k polynomial at n distinct points so any k of n symbols recover the message.",
      "RAID-6 and object stores use that MDS property as disk insurance. Singleton says you tolerate n−k erasures.",
      "Storage products reconstruct. They do not receipt the recovered digest against a governance bound.",
    ],
    delta:
      "ShardWitness is an RS(10,6) evaluation code over GF(257). Recoverable iff ≥ 6 of 10 shards. Receipt the recovered coefficients. CHECKED ≠ Lean F18 PROVEN. Not RAID. Not a storage product.",
    frontier: "ShardWitness",
    frontierId: "shard",
    live: true,
    honesty: "LIVE",
    silhouette: "erasure coding / RAID-6",
  },
  {
    id: "evidence-bay",
    n: 19,
    szl: "szl-evidence-bay",
    repo: "szl-holdings/szl-khipu",
    leader: "OpenTelemetry / Dapper / observability dashboards",
    paper: "Dapper, Google 2010 · OpenTelemetry specification",
    paperUrl: "https://opentelemetry.io/docs/specs/otel/",
    repoUrl: "https://github.com/open-telemetry/opentelemetry-specification",
    leaderSummary: [
      "Dapper and OpenTelemetry made distributed traces the default way to watch a system. Dashboards collapse transport, evidence, and authority into one pane.",
      "A green probe is not a signed receipt. A RUNNING service is not proof that the RECORD moved.",
      "The category is observability. It does not keep proof on a separate origin from the product.",
    ],
    delta:
      "Evidence Bay is four rails: transport, evidence, verification, authority. Collapse any two and the body fail-closes. Hub listings stay transport. RECORD stays on a11oy.net. a-11-oy.com operates. Never a11oy.com.",
    frontier: "Evidence Bay",
    frontierId: "bay",
    live: true,
    honesty: "LIVE",
    silhouette: "observability / proof-product split",
  },
  {
    id: "greenlight",
    n: 20,
    szl: "szl-greenlight",
    repo: "szl-holdings/szl-khipu",
    leader: "Continuous Integration / required status checks",
    paper: "Continuous Integration · Fowler 2006 · GitHub required status checks",
    paperUrl: "https://martinfowler.com/articles/continuousIntegration.html",
    repoUrl: "https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks",
    leaderSummary: [
      "Fowler’s CI made a green build the merge predicate. GitHub required status checks turned that green into a branch-protection bit.",
      "A required check can pass while a sorry is still a hole, while Λ uniqueness stays OPEN, while energy is UNAVAILABLE.",
      "The category is ‘the build is green.’ It does not refuse to paint a conjecture as a theorem.",
    ],
    delta:
      "GreenLight is a fail-closed promotion predicate, the dual of WILLAY. Honest ALLOW on a LIVE proved bound. Paint a sorry green, claim proven_trust, or stamp a fabricated joule and the light stays BLOCKED. Never amber. proven_trust locked false. Energy UNAVAILABLE.",
    frontier: "GreenLight",
    frontierId: "greenlight",
    live: true,
    honesty: "LIVE",
    silhouette: "CI green / merge queue",
  },
  {
    id: "tile-digest",
    n: 21,
    szl: "szl-tile-digest",
    repo: "szl-holdings/szl-khipu",
    leader: "FlashAttention tiling / online softmax (Dao 2022, Milakov & Gimelshein 2018)",
    paper: "FlashAttention · arXiv:2205.14135 · Online softmax 2018",
    paperUrl: "https://arxiv.org/abs/2205.14135",
    repoUrl: "https://github.com/Dao-AILab/flash-attention",
    leaderSummary: [
      "Dao et al. tile Q into Br rows and K/V into Bc columns, then fold each block with online softmax so exact attention never writes S or P to HBM.",
      "FlashAttention-2 makes the outer loop the Q tiles. The schedule is an implementation detail of the speed kernel.",
      "A correct output does not prove the kernel ran the Br×Bc grid it claimed.",
    ],
    delta:
      "TileDigest receipts the Br×Bc schedule: hash(n, d, Br, Bc, tiles). Cover must be exact. Claim a coarser Br or drop a K-tile and the bound fail-closes even if residual-vs-naive still holds. Not a CUDA rehost. No tokens/s claim.",
    frontier: "TileDigest",
    frontierId: "tiledigest",
    live: true,
    honesty: "LIVE",
    silhouette: "attention tile schedule",
  },
];

export const LIVE_FRONTIERS = ATLAS.filter((r) => r.live);

export function rowByFrontier(id: string) {
  return ATLAS.find((r) => r.frontierId === id) ?? LIVE_FRONTIERS[0];
}
