import type { FormulaSpec } from "@/lib/types";

/** Lab-numeric identities. NOT the Lean locked-8. CHECKED ≠ PROVEN. */
export const FORMULAS: FormulaSpec[] = [
  {
    id: "f.parseval",
    slug: "parseval",
    name: "Parseval (unitary DFT)",
    quechua: "Tupu Q'uñi",
    statement: "Energy in time equals energy in frequency. Lab numeric, not F1.",
    lhs: "Σ x²",
    rhs: "(1/N) Σ |X|²",
    epsilon: 1e-5,
    lockedProven: false,
  },
  {
    id: "f.cauchy",
    slug: "cauchy",
    name: "Cauchy–Schwarz",
    quechua: "Tupu Yupay",
    statement: "⟨u,v⟩² ≤ ‖u‖² ‖v‖²",
    lhs: "⟨u,v⟩²",
    rhs: "‖u‖² ‖v‖²",
    epsilon: 1e-9,
    lockedProven: false,
  },
  {
    id: "f.wgm-max",
    slug: "wgm-max",
    name: "WGM bounded by max (A4)",
    quechua: "Kamachiq",
    statement: "Λ(x) ≤ max x_i. Uniqueness of Λ is Conjecture 1 — OPEN.",
    lhs: "Λ(x)",
    rhs: "max x_i",
    epsilon: 1e-12,
    lockedProven: false,
  },
  {
    id: "f.wgm-homog",
    slug: "wgm-homog",
    name: "WGM A2+A3+A4 bundle",
    quechua: "Kamachiq",
    statement: "Homogeneous, Egyptian-exact, bounded. Not a uniqueness proof.",
    lhs: "axiom bundle",
    rhs: "pass",
    epsilon: 0,
    lockedProven: false,
  },
  {
    id: "f.zero-route",
    slug: "zero-route",
    name: "Zero-routing",
    quechua: "Kamachiq",
    statement: "Any axis at 0 forces Λ = 0. Non-compensatory.",
    lhs: "Λ(x with a 0)",
    rhs: "0",
    epsilon: 0,
    lockedProven: false,
  },
  {
    id: "f.softmax",
    slug: "softmax",
    name: "Softmax partition",
    quechua: "Tupu Q'uñi",
    statement: "Each softmax row sums to 1.",
    lhs: "Σ_j softmax(S)_ij",
    rhs: "1",
    epsilon: 1e-6,
    lockedProven: false,
  },
  {
    id: "f.rms",
    slug: "rms",
    name: "RMSNorm unit RMS",
    quechua: "Tupu Rumi",
    statement: "After RMSNorm, RMS(y / γ) ≈ 1 (ε in the kernel).",
    lhs: "RMS(y / γ)",
    rhs: "1",
    epsilon: 1e-4,
    lockedProven: false,
  },
  {
    id: "f.attn-err",
    slug: "attn-err",
    name: "Tile vs naive",
    quechua: "Tupu Q'uñi",
    statement: "Online-softmax tiled attention matches naive within ε.",
    lhs: "max |O_tile − O_naive|",
    rhs: "0",
    epsilon: 1e-5,
    lockedProven: false,
  },
];

export const LOCKED_EIGHT = [
  { id: "F1", name: "Replay-Hash Determinism", caveat: "" },
  { id: "F4", name: "Khipu DAG acyclicity", caveat: "edges dst < src" },
  { id: "F7", name: "Chaski FIFO", caveat: "drain(enqueueAll([], msgs)) = msgs" },
  { id: "F11", name: "Ayni Reciprocity Conservation", caveat: "Σ in = Σ out" },
  {
    id: "F12",
    name: "Kuramoto boundedness",
    caveat: "additive fragment ONLY — not full nonlinear sync",
  },
  { id: "F18", name: "RS(10,6) recovery", caveat: "recoverable iff ≥ 6 of 10 shards" },
  {
    id: "F19",
    name: "Bekenstein additive scaffolding",
    caveat: "monotone fragment ONLY — not S ≤ 2πkRE/ℏc",
  },
  { id: "F22", name: "Khipu emit monotonicity", caveat: "sequence numbers strictly increase" },
] as const;

export const LOCKED_PROVEN = LOCKED_EIGHT.length;
