import type { Frontier } from "@/lib/types";

export const DEFAULT_FRONTIERS: Frontier[] = [
  {
    id: "chaski",
    name: "Chaski FIFO",
    subject: { kind: "kernel", id: "k.chaski" },
    metric: "broken",
    best: 1,
    direction: "min",
    receiptId: null,
    attempts: 0,
    beatenAt: null,
  },
  {
    id: "ayni",
    name: "Ayni Reciprocity",
    subject: { kind: "kernel", id: "k.ayni" },
    metric: "leak",
    best: 1e-3,
    direction: "min",
    receiptId: null,
    attempts: 0,
    beatenAt: null,
  },
  {
    id: "shard",
    name: "ShardWitness RS(10,6)",
    subject: { kind: "kernel", id: "k.shard" },
    metric: "recovered",
    best: 0,
    direction: "max",
    receiptId: null,
    attempts: 0,
    beatenAt: null,
  },
  {
    id: "bay",
    name: "Evidence Bay rails",
    subject: { kind: "kernel", id: "k.bay" },
    metric: "collapsed",
    best: 1,
    direction: "min",
    receiptId: null,
    attempts: 0,
    beatenAt: null,
  },
  {
    id: "tilereceipt",
    name: "Tile vs naive residual",
    subject: { kind: "kernel", id: "k.attn" },
    metric: "residual",
    best: 1e-5,
    direction: "min",
    receiptId: null,
    attempts: 0,
    beatenAt: null,
  },
  {
    id: "canal",
    name: "Canal leak",
    subject: { kind: "kernel", id: "k.yarqa" },
    metric: "leaked",
    best: 1e-9,
    direction: "min",
    receiptId: null,
    attempts: 0,
    beatenAt: null,
  },
  {
    id: "organ",
    name: "Organ integrity (5/5)",
    subject: { kind: "kernel", id: "k.anatomy" },
    metric: "blocked",
    best: 1,
    direction: "min",
    receiptId: null,
    attempts: 0,
    beatenAt: null,
  },
  {
    id: "looptax",
    name: "Loop-tax halt",
    subject: { kind: "kernel", id: "k.frontier" },
    metric: "blocked",
    best: 1,
    direction: "min",
    receiptId: null,
    attempts: 0,
    beatenAt: null,
  },
  {
    id: "moons-loss",
    name: "Moons NLL",
    subject: { kind: "model", id: "m.mlp" },
    metric: "loss",
    best: 0.22,
    direction: "min",
    receiptId: null,
    attempts: 0,
    beatenAt: null,
  },
  {
    id: "abstain",
    name: "TinyKhipu abstain",
    subject: { kind: "model", id: "m.khipu" },
    metric: "abstain",
    best: 0.66,
    direction: "max",
    receiptId: null,
    attempts: 0,
    beatenAt: null,
  },
];
