import type { Honesty } from "@/lib/types";

export type EstateModel = {
  id: string;
  hub: string;
  name: string;
  class: "qlora" | "surrogate" | "statistical" | "stub";
  params: string;
  trainableHere: boolean;
  honesty: Honesty;
  eval: string;
  whatNot: string;
};

export const ESTATE_MODELS: EstateModel[] = [
  {
    id: "tinykhipu-nano",
    hub: "SZLHOLDINGS/TinyKhipu-Nano",
    name: "TinyKhipu-Nano",
    class: "surrogate",
    params: "few-thousand floats",
    trainableHere: true,
    honesty: "LIVE",
    eval: "plan-valid 1.00 · abstain 1.00 · hallucinated 0",
    whatNot: "Not Qwen. Not 1.5B. Hard ID filter. Honesty REPORTED.",
  },
  {
    id: "receiptagent-nano",
    hub: "SZLHOLDINGS/ReceiptAgent-Nano",
    name: "ReceiptAgent-Nano",
    class: "surrogate",
    params: "24-16-8-4",
    trainableHere: true,
    honesty: "LIVE",
    eval: "held-out agree 0.905 · kernel is truth",
    whatNot: "Does not override rule_check. Not 1.5B. Not Qwen.",
  },
  {
    id: "szl-khipu-pkg",
    hub: "SZLHOLDINGS/szl-khipu",
    name: "szl-khipu",
    class: "statistical",
    params: "NumPy package 0.1.0",
    trainableHere: true,
    honesty: "LIVE",
    eval: "38 unit tests · CPU numpy LIVE · CUDA UNAVAILABLE",
    whatNot: "Not a FlashAttention rehost. Λ uniqueness OPEN.",
  },
  {
    id: "moons-nano",
    hub: "SZLHOLDINGS/Moons-Nano",
    name: "Moons-Nano",
    class: "surrogate",
    params: "2→8→2",
    trainableHere: true,
    honesty: "LIVE",
    eval: "acc 0.93 · loss ~0.13 · REPORTED on training moons",
    whatNot: "Not 1.5B. Not a published benchmark. Energy UNAVAILABLE.",
  },
  {
    id: "miniembed-nano",
    hub: "SZLHOLDINGS/MiniEmbed-Nano",
    name: "MiniEmbed-Nano",
    class: "statistical",
    params: "V=64 d=12",
    trainableHere: true,
    honesty: "LIVE",
    eval: "hash+table L2 · not neural",
    whatNot: "Not the 3290×128 MiniEmbed on szl-kernels. No analogy score.",
  },
  {
    id: "khipu-1.5b",
    hub: "SZLHOLDINGS/SZL-Khipu-1.5B",
    name: "SZL-Khipu-1.5B",
    class: "qlora",
    params: "1.54B base · QLoRA",
    trainableHere: false,
    honesty: "RESEARCH",
    eval: "plan-valid 11/11 · grounding 4/5 · abstain 2/6 (blocker)",
    whatNot: "Not from-scratch. Not autonomous. Curriculum unpublished.",
  },
  {
    id: "khipu-r2",
    hub: "SZLHOLDINGS/KHIPU-R2",
    name: "KHIPU-R2",
    class: "qlora",
    params: "1.54B · r=32 α=64",
    trainableHere: false,
    honesty: "RESEARCH",
    eval: "abstain 3/6 — MEASURED, not a pass",
    whatNot: "Does not overwrite signed 1.5B. Not publication-eligible.",
  },
  {
    id: "receiptagent-1.5b",
    hub: "SZLHOLDINGS/SZL-Forge-1.5B-ReceiptAgent",
    name: "ReceiptAgent 1.5B",
    class: "qlora",
    params: "1.54B · QLoRA",
    trainableHere: false,
    honesty: "RESEARCH",
    eval: "draft 5/5 · refusal 6/6 · tiny N",
    whatNot: "Proposal-only. Never executes. GGUF not in signed hash.",
  },
  {
    id: "receiptagent-0.8b",
    hub: "SZLHOLDINGS/szl-receiptagent-qwen35-0.8b-v2",
    name: "ReceiptAgent 0.8B v2",
    class: "qlora",
    params: "10.8M trainable / 864M",
    trainableHere: false,
    honesty: "RESEARCH",
    eval: "JSON 5/5 · refusal 6/6",
    whatNot: "A11oy Brain corpus excluded. Autonomy false.",
  },
  {
    id: "chaski",
    hub: "SZLHOLDINGS/chaski",
    name: "chaski",
    class: "qlora",
    params: "Qwen3.5-0.8B QLoRA",
    trainableHere: false,
    honesty: "RESEARCH",
    eval: "json_draft 0/5 · refusal 2/6 · FAIL kept",
    whatNot: "Honest fail card. publication_eligible false.",
  },
  {
    id: "miniembed",
    hub: "SZLHOLDINGS/szl-kernels",
    name: "MiniEmbed",
    class: "statistical",
    params: "3290 × 128 = 421,120 f32",
    trainableHere: true,
    honesty: "LIVE",
    eval: "SVD var 0.3146 · NN Jaccard ≥ 0.90 replay",
    whatNot: "Not neural. No analogy or retrieval score.",
  },
  {
    id: "lambda-surrogate",
    hub: "SZLHOLDINGS/szl-lambda-gate",
    name: "Λ-gate surrogate",
    class: "surrogate",
    params: "9.28k MLP",
    trainableHere: true,
    honesty: "ADVISORY",
    eval: "held-out fidelity 0.9670 vs kernel",
    whatNot: "Kernel is ground truth. Uniqueness = Conjecture 1 OPEN.",
  },
  {
    id: "szl-nemo-hub",
    hub: "SZLHOLDINGS/szl-nemo",
    name: "szl-nemo (Hub)",
    class: "surrogate",
    params: "sklearn TF-IDF+LR",
    trainableHere: true,
    honesty: "UNAVAILABLE",
    eval: "fidelity 1.0 vs rule_check · joblib missing",
    whatNot: "Not Nemotron. Not an LLM. Blob unpublished.",
  },
  {
    id: "willay",
    hub: "SZLHOLDINGS/WILLAY",
    name: "WILLAY",
    class: "stub",
    params: "roadmap",
    trainableHere: false,
    honesty: "ROADMAP",
    eval: "no weights",
    whatNot: "Signed-refusal specialist. Do not treat as trained.",
  },
  {
    id: "a11oy-mini",
    hub: "SZLHOLDINGS/A11OY-MINI",
    name: "A11OY-MINI",
    class: "stub",
    params: "~0.8B proposal",
    trainableHere: false,
    honesty: "ROADMAP",
    eval: "no signed eval receipt",
    whatNot: "Convenience card until a signed eval exists.",
  },
];

export const TINY_TRAINABLE = ESTATE_MODELS.filter((m) => m.trainableHere);
