/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RailsRouteImport } from './routes/rails'
import { Route as LabPlayRouteImport } from './routes/lab.$play'
import { Route as InspectKindIdRouteImport } from './routes/inspect.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RailsRoute = RailsRouteImport.update({
  id: '/rails',
  path: '/rails',
  getParentRoute: () => rootRouteImport,
} as any)
const LabPlayRoute = LabPlayRouteImport.update({
  id: '/lab/$play',
  path: '/lab/$play',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectKindIdRoute = InspectKindIdRouteImport.update({
  id: '/inspect/$kind/$id',
  path: '/inspect/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rails': typeof RailsRoute
  '/lab/$play': typeof LabPlayRoute
  '/inspect/$kind/$id': typeof InspectKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rails': typeof RailsRoute
  '/lab/$play': typeof LabPlayRoute
  '/inspect/$kind/$id': typeof InspectKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rails': typeof RailsRoute
  '/lab/$play': typeof LabPlayRoute
  '/inspect/$kind/$id': typeof InspectKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rails' | '/lab/$play' | '/inspect/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rails' | '/lab/$play' | '/inspect/$kind/$id'
  id: '__root__' | '/' | '/rails' | '/lab/$play' | '/inspect/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RailsRoute: typeof RailsRoute
  LabPlayRoute: typeof LabPlayRoute
  InspectKindIdRoute: typeof InspectKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rails': {
      id: '/rails'
      path: '/rails'
      fullPath: '/rails'
      preLoaderRoute: typeof RailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$play': {
      id: '/lab/$play'
      path: '/lab/$play'
      fullPath: '/lab/$play'
      preLoaderRoute: typeof LabPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$kind/$id': {
      id: '/inspect/$kind/$id'
      path: '/inspect/$kind/$id'
      fullPath: '/inspect/$kind/$id'
      preLoaderRoute: typeof InspectKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RailsRoute: RailsRoute,
  LabPlayRoute: LabPlayRoute,
  InspectKindIdRoute: InspectKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
